### ISSUE TITLE
profile doesn't work with simulation mission

### ISSUE THREAD

**Issue by melanybelzile** [DFOglider/pilotingApp#16] opened 2018-04-18 17:09 UTC

**Comment by richardsc** [comment] 2018-04-23 22:35
I suspect this has something to do with the `profiles` code

**Comment by richardsc** [comment] 2018-05-14 18:44
The problem is at line 224 of app.R:
```r
# profile numbers    
    profiles <- unlist(lapply(dnctd, function(k) k@metadata[['station']]))   
```
```
Warning: Error in FUN: trying to get slot "metadata" from an object of a basic class ("logical") with no slots
```
It's likely happening because the payload pressure sensor is not actually changing, and so the profile detection algorithm doesn't work.

The proposed solution is to detect when it's a simulation by looking at the difference of the range of the payload pressure sensor, and if it's small (say <5 dbar) we just interpolate the NAV pressures to the PLD pressures

**Comment by clayton33** [comment] 2018-05-14 19:17
the issue above with regards to line 224 has been addressed by doing what was suggested by @richardsc, leaving this issue open for future simulation mode problems

**Comment by richardsc** [comment] 2018-05-14 21:21
I tested this on the shiny server after a restart, and it looks good. 

Closing.

**Closed as completed by richardsc** 2018-05-14 21:21 UTC
